let s:minpac_dir = $HOME . '/.vim/pack/minpac/opt/minpac'

if has('vim_starting')
  if !isdirectory(s:minpac_dir)
    echo "Install minpac ..."
    execute '!git clone --depth 1 https://github.com/k-takata/minpac ' . s:minpac_dir
  endif
endif

if &compatible
  " `:set nocp` has many side effects. Therefore this should be done
  " only when 'compatible' is set.
  set nocompatible
endif

packadd minpac
call minpac#init()

if exists('*minpac#init')
  " packadd minpac
  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})

  " prettier
  call minpac#add('prettier/vim-prettier')

  " tpope plugins!
  call minpac#add('tpope/vim-surround')
  call minpac#add('tpope/vim-repeat')
  call minpac#add('tpope/vim-commentary')
  call minpac#add('tpope/vim-unimpaired')
  call minpac#add('tpope/vim-fugitive')
  call minpac#add('tpope/vim-scriptease', { 'type': 'opt' })
  " this is for Gbrowse
  call minpac#add('tpope/vim-rhubarb')

  call minpac#add('github/copilot.vim')

  " additional text objects
  call minpac#add('kana/vim-textobj-entire')
  call minpac#add('kana/vim-textobj-user')
  call minpac#add('kana/vim-textobj-indent')
  call minpac#add('thinca/vim-textobj-between')

  " for note taking
  call minpac#add('vimwiki/vimwiki')
  call minpac#add('mattn/calendar-vim')

  " file manager and jump
  call minpac#add('justinmk/vim-dirvish')
  call minpac#add('justinmk/vim-sneak')

  " colors
  call minpac#add('gruvbox-community/gruvbox')
  call minpac#add('ayu-theme/ayu-vim')

  " misc
  call minpac#add('capaj/vscode-standardjs-snippets')
  call minpac#add('cespare/vim-toml')
  call minpac#add('yuezk/vim-js')
  call minpac#add('MaxMEllon/vim-jsx-pretty')
  call minpac#add('leafOfTree/vim-svelte-plugin')

  " general enhancements
  call minpac#add('editorconfig/editorconfig-vim')
  call minpac#add('christoomey/vim-tmux-navigator')
  call minpac#add('romainl/vim-cool')
  call minpac#add('mattn/emmet-vim')
  call minpac#add('dag/vim-fish')
  " call minpac#add('jsfaint/gen_tags.vim')
  " call minpac#add('ajh17/VimCompletesMe')

  call minpac#add('junegunn/vim-easy-align')
  call minpac#add('junegunn/fzf', {'type': 'opt'})
  call minpac#add('junegunn/fzf.vim', {'type': 'opt'})
endif

" settings
runtime settings/general.vim
runtime settings/colors.vim
runtime settings/mappings.vim
runtime settings/statusline.vim
runtime settings/format.vim
runtime settings/functions.vim

" plugin settings
runtime plugins/vimwiki.vim
runtime plugins/dirvish.vim
runtime plugins/vim-sneak.vim
runtime plugins/easyalign.vim
runtime plugins/emmet.vim
runtime plugins/fzf.vim

command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update('', {'do': 'call minpac#status()'})
command! PackClean  packadd minpac | source $MYVIMRC | call minpac#clean()
command! PackStatus packadd minpac | source $MYVIMRC | call minpac#status()

